=== jedi-academy/example-simplexml-winter2016/data/timetable.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT timestable (day, timeslot, course)>
<!ATTLIST timestable year (2016) #REQUIRED term (1|2|3|4) #REQUIRED>

<!ELEMENT day (schedule)>
<!ATTLIST day date (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED>

<!ELEMENT timeslot (schedule)>
<!ATTLIST timeslot time (8:30|9:30|10:30|11:30|12:30|1:30|2:30|3:30|4:30|5:30) #REQUIRED>

<!ELEMENT course (schedule)>
<!ATTLIST course classProgram CDATA "COMP"
                 classNumber CDATA #REQUIRED
                 classTitle CDATA #REQUIRED
>

<!ELEMENT schedule (chooseTimeslot, chooseCourse, chooseDay, room, instructor)>
<!ATTLIST booking classType (Lecture|Lab) #REQUIRED>

<!ELEMENT chooseTimeslot (#PCDATA)>
<!ELEMENT chooseCourse (#PCDATA)>
<!ELEMENT chooseDay (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>

=== jedi-academy/example-simplexml-winter2016/data/myCourses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE timestable SYSTEM "timetable.dtd">

<timestable year="2016" term="4">
  <day date="Wednesday">
    <schedule classType="Lecture">
      <chooseTimeslot>"9:30"</chooseTimeslot>
      <chooseCourse>"COMP 4945"</chooseCourse>
      <chooseDay>"Wednesday"</chooseDay>
      <room>"SE12 319"</room>
      <instructor>"Tejinder Randhawa"</instructor>
    </schedule>
  </day>
  <timeslot time="9:30">
    <schedule classType="Lab">
      <chooseTimeslot>"9:30"</chooseTimeslot>
      <chooseCourse>"COMP 4945"</chooseCourse>
      <chooseDay>"Wednesday"</chooseDay>
      <room>"SE12 319"</room>
      <instructor>"Tejinder Randhawa"</instructor>
    </schedule>
  </timeslot>
  <course classNumber="COMP 4945" classTitle="Client Server">
    <schedule classType="Lecture">
      <chooseTimeslot>"9:30"</chooseTimeslot>
      <chooseCourse>"COMP 4945"</chooseCourse>
      <chooseDay>"Wednesday"</chooseDay>
      <room>"SE12 319"</room>
      <instructor>"Tejinder Randhawa"</instructor>
    </schedule>
  </course>
</timestable>
